######################## default configuration ####################
baseURL = "http://aristaequis.com/"
title = "aristaequis - Transformación Digital"
defaultContentLanguage = "es"
theme = "bigspring"
# post pagination
paginate = "50"
# post excerpt
summaryLength = "70"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "" # example : UA-123-45
# Google Analytics 4
googleAnalyticsID = "G-9YFMJ98Q45"
# unsafe html
[markup.goldmark.renderer]
unsafe = true