############################# Spanish ############################
[es]
languageName = "Español"
title = "aristaequis - Transformación Digital"
contentDir = "content/spanish" # content/spanish
weight = 1
########### footer content ##########
footer_menu_left = "Acerca"
footer_menu_middle = "Blog"
footer_menu_right = "Soporte"
footer_content = "Experiencia y tecnología innovadora que transforma tu empresa."
# copyright
copyright = "© aristaequis 2021"

############################# English ############################
[en]
languageName = "English"
title = "aristaequis - Digital Transformation"
contentDir = "content/english" # content/english
weight = 2
############ footer content ##########
footer_menu_left = "About"
footer_menu_middle = "Blog"
footer_menu_right = "Support"
#footer_content = "Experience and innovative technology that transforms your company."
# copyright
copyright = "© aristaequis 2021"