#################### default parameters ################################
logo = "images/logo.png"
logo_width = "200px"
# OpenGraph / Twitter Card metadata
description = "Experiencia y tecnología innovadora que transforma tu empresa"
author = "alfons_mr"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[navigation_button]
enable = true
label = "Contactar"
link = "contact"

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"
  
############################# social site ########################
[[social]]
title = "facebook"
icon = "fab fa-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/aristaequisTD"

[[social]]
title = "twitter"
icon = "fab fa-twitter" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/alfons_mr"

#[[social]]
#title = "skype"
#icon = "fab fa-skype" # themify icon : https://themify.me/themify-icons
#link = "#"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/in/alfonsmr/"